FROM python:3

RUN mkdir /scripts
WORKDIR /scripts
VOLUME /srv
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY utils.py /scripts
CMD [ "python", "/scripts/utils.py" ]
