# vim: ft=dockerfile
FROM alpine:latest
RUN mkdir /config
RUN mkdir /scripts
VOLUME /config
VOLUME /srv
WORKDIR /scripts
RUN ln -s /config /root/.newsboat
COPY podcast.py /scripts/podcast.py
COPY podcast.sh /scripts/podcast.sh
COPY toopus.sh /scripts/toopus.sh
ENTRYPOINT ./podcast.sh -DFOREGROUND
ARG CACHEBUST
RUN apk add --no-cache python3 py3-pip ffmpeg newsboat py3-requests py3-slugify py3-setuptools opus-tools bash parallel
RUN pip3 install r128gain
